In [81]:
from jugaad_data.nse import stock_df
from datetime import date
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [94]:
companies = [
    "HDFCBANK",
    "RELIANCE",
    "SBIN",
    "LT",
    "ICICIBANK",
    "MARUTI"
]

all_data = []

for company in companies:

    temp = stock_df(
        symbol=company,
        from_date=date(2024, 1, 1),
        to_date=date(2026, 9, 7),
        series="EQ"
    )

    temp["Company"] = company

    all_data.append(temp)

df = pd.concat(all_data, ignore_index=True)

c:\Users\Anish Kumar\AppData\Local\Programs\Python\Python311\Lib\site-packages\jugaad_data\util.py:40: UserWarning: no explicit representation of timezones available for np.datetime64
  return np.datetime64(dt)
c:\Users\Anish Kumar\AppData\Local\Programs\Python\Python311\Lib\site-packages\jugaad_data\util.py:40: UserWarning: no explicit representation of timezones available for np.datetime64
  return np.datetime64(dt)
c:\Users\Anish Kumar\AppData\Local\Programs\Python\Python311\Lib\site-packages\jugaad_data\util.py:40: UserWarning: no explicit representation of timezones available for np.datetime64
  return np.datetime64(dt)
c:\Users\Anish Kumar\AppData\Local\Programs\Python\Python311\Lib\site-packages\jugaad_data\util.py:40: UserWarning: no explicit representation of timezones available for np.datetime64
  return np.datetime64(dt)
c:\Users\Anish Kumar\AppData\Local\Programs\Python\Python311\Lib\site-packages\jugaad_data\util.py:40: UserWarning: no explicit representation of timezones available for np.datetime64
  return np.datetime64(dt)
c:\Users\Anish Kumar\AppData\Local\Programs\Python\Python311\Lib\site-packages\jugaad_data\util.py:40: UserWarning: no explicit representation of timezones available for np.datetime64
  return np.datetime64(dt)

In [95]:
hdfc = df[df["Company"] == "HDFCBANK"]

In [88]:
hdfc

,DATE,SERIES,OPEN,HIGH,LOW,PREV. CLOSE,LTP,CLOSE,VWAP,VOLUME,VALUE,NO OF TRADES,DELIVERY QTY,DELIVERY %,SYMBOL,Company
0,2026-09-03 18:30:00,EQ,708.35,716.50,708.35,706.65,712.10,712.10,713.56,14488024,1.033815e+10,202544,8371615,57.78,HDFCBANK,HDFCBANK
1,2026-09-02 18:30:00,EQ,705.00,712.60,705.00,700.80,706.65,706.65,708.33,27770641,1.967064e+10,293146,16590339,59.74,HDFCBANK,HDFCBANK
2,2026-09-01 18:30:00,EQ,702.30,705.65,700.00,711.90,700.80,700.80,702.22,36950338,2.594712e+10,475283,22751679,61.57,HDFCBANK,HDFCBANK
3,2026-08-31 18:30:00,EQ,705.05,715.45,698.50,709.00,711.90,711.90,707.88,44417092,3.144201e+10,509180,18568849,41.81,HDFCBANK,HDFCBANK
4,2026-08-30 18:30:00,EQ,723.05,739.75,704.15,720.30,709.00,709.00,720.91,78157067,5.634412e+10,763649,41701133,53.36,HDFCBANK,HDFCBANK
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
672,2024-01-04 18:30:00,EQ,1687.15,1704.90,1668.10,1690.85,1679.00,1682.20,1679.44,15944735,2.677825e+10,426162,9617611,60.32,HDFCBANK,HDFCBANK
673,2024-01-03 18:30:00,EQ,1678.00,1694.95,1670.70,1672.90,1690.85,1690.85,1681.98,13367028,2.248313e+10,335934,9457028,70.75,HDFCBANK,HDFCBANK
674,2024-01-02 18:30:00,EQ,1702.00,1704.70,1668.95,1699.10,1674.60,1672.90,1681.27,14194881,2.386541e+10,426015,8613392,60.68,HDFCBANK,HDFCBANK
675,2024-01-01 18:30:00,EQ,1698.80,1702.80,1688.70,1698.10,1697.50,1699.10,1697.43,14621046,2.481815e+10,334886,8690628,59.44,HDFCBANK,HDFCBANK
676,2023-12-31 18:30:00,EQ,1706.00,1709.15,1692.00,1709.25,1692.90,1698.10,1701.52,7119843,1.211457e+10,258349,4416670,62.03,HDFCBANK,HDFCBANK

In [98]:
MSI = df[df["Company"] ==  "MARUTI"]

In [99]:
MSI

,DATE,SERIES,OPEN,HIGH,LOW,PREV. CLOSE,LTP,CLOSE,VWAP,VOLUME,VALUE,NO OF TRADES,DELIVERY QTY,DELIVERY %,SYMBOL,Company
3403,2026-09-03 18:30:00,EQ,12880.00,12880.0,12656.00,12857.00,12694.0,12694.00,12728.92,322752,4.108283e+09,65754,182259,56.47,MARUTI,MARUTI
3404,2026-09-02 18:30:00,EQ,12853.00,12927.0,12780.00,12849.00,12857.0,12857.00,12866.77,362982,4.670406e+09,50136,169374,46.66,MARUTI,MARUTI
3405,2026-09-01 18:30:00,EQ,12763.00,12888.0,12640.00,12950.00,12849.0,12849.00,12728.06,614156,7.817013e+09,115523,362918,59.09,MARUTI,MARUTI
3406,2026-08-31 18:30:00,EQ,13540.00,13540.0,12851.00,13547.00,12950.0,12950.00,13035.49,915975,1.194018e+10,139177,487317,53.20,MARUTI,MARUTI
3407,2026-08-30 18:30:00,EQ,13375.00,13547.0,13268.00,13376.00,13547.0,13547.00,13410.78,443131,5.942733e+09,58741,298886,67.45,MARUTI,MARUTI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4065,2024-01-04 18:30:00,EQ,10010.65,10075.0,9970.00,10015.30,10000.0,10017.00,10008.08,673131,6.736751e+09,105880,468881,69.66,MARUTI,MARUTI
4066,2024-01-03 18:30:00,EQ,10100.00,10120.0,9985.55,10077.65,9995.0,10015.30,10012.71,711733,7.126374e+09,130325,529829,74.44,MARUTI,MARUTI
4067,2024-01-02 18:30:00,EQ,10200.00,10210.0,10065.00,10197.75,10068.0,10077.65,10101.72,521046,5.263461e+09,90507,380089,72.95,MARUTI,MARUTI
4068,2024-01-01 18:30:00,EQ,10283.30,10294.7,10151.05,10283.30,10190.0,10197.75,10202.56,776837,7.925728e+09,121457,564333,72.64,MARUTI,MARUTI
4069,2023-12-31 18:30:00,EQ,10345.00,10345.0,10214.65,10302.35,10270.0,10283.30,10274.79,411724,4.230379e+09,58748,255206,61.98,MARUTI,MARUTI