In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
dc = pd.read_csv(r"C:\Users\Anish Kumar\OneDrive\Documents\GitHub\PANDAS-CURSE\smart_city_urban_life_analysis_Project\cleaned_data.csv")

In [3]:
dc.head(5)

,Record_ID,Date,Day_Name,City,Area_Type,Citizen_ID,Age_Group,Work_Mode,Temperature_C,Rainfall_mm,...,Work_Hours,Outdoor_Activity_Hours,Happiness_Score,Service_Satisfaction,Weekend,Month,Year,Day,Month_Name,Quarter
0,REC000001,2024-07-17,Wednesday,Mumbai,Residential,CIT356787,25-34,Office,31.4,0.7,...,10.2,4.2,8.7,8.4,No,7,2024,17,July,3
1,REC000002,2025-01-05,Sunday,Mumbai,Residential,CIT988662,25-34,Hybrid,21.2,2.5,...,6.2,1.8,8.7,9.0,Yes,1,2025,5,January,1
2,REC000003,2024-12-28,Saturday,Hyderabad,Residential,CIT319684,35-44,Office,20.6,2.0,...,8.3,2.0,8.8,10.0,Yes,12,2024,28,December,4
3,REC000004,2023-10-13,Friday,Jaipur,Residential,CIT358607,35-44,Other,21.8,0.5,...,0.5,0.8,5.3,7.6,No,10,2023,13,October,4
4,REC000005,2023-08-23,Wednesday,Delhi,Commercial,CIT814825,45-54,Hybrid,29.3,2.8,...,7.0,2.4,8.9,10.0,No,8,2023,23,August,3

In [4]:
dc.tail(5)

,Record_ID,Date,Day_Name,City,Area_Type,Citizen_ID,Age_Group,Work_Mode,Temperature_C,Rainfall_mm,...,Work_Hours,Outdoor_Activity_Hours,Happiness_Score,Service_Satisfaction,Weekend,Month,Year,Day,Month_Name,Quarter
99995,REC099996,2025-11-21,Friday,Chennai,Industrial,CIT227256,18-24,Hybrid,27.0,3.4,...,8.9,2.2,7.8,6.6,No,11,2025,21,November,4
99996,REC099997,2023-05-26,Friday,Bengaluru,Residential,CIT834022,45-54,Work From Home,28.5,0.2,...,6.1,1.9,8.7,9.0,No,5,2023,26,May,2
99997,REC099998,2024-10-27,Sunday,Kolkata,Mixed Use,CIT455598,18-24,Other,24.3,2.7,...,3.0,3.4,9.2,8.1,Yes,10,2024,27,October,4
99998,REC099999,2023-09-14,Thursday,Chennai,Mixed Use,CIT721668,18-24,Office,30.5,0.5,...,7.8,4.6,10.0,9.5,No,9,2023,14,September,3
99999,REC100000,2025-12-04,Thursday,Hyderabad,Residential,CIT170780,18-24,Hybrid,23.3,1.8,...,6.8,2.1,7.9,8.3,No,12,2025,4,December,4

In [5]:
dc.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   Record_ID                       100000 non-null  str
 1   Date                            100000 non-null  str
 2   Day_Name                        100000 non-null  str
 3   City                            100000 non-null  str
 4   Area_Type                       100000 non-null  str
 5   Citizen_ID                      100000 non-null  str
 6   Age_Group                       100000 non-null  str
 7   Work_Mode                       100000 non-null  str
 8   Temperature_C                   100000 non-null  float64
 9   Rainfall_mm                     100000 non-null  float64
 10  AQI                             100000 non-null  float64
 11  Traffic_Level                   100000 non-null  str
 12  Average_Traffic_Speed_kmh       100000 non-null  float64
 13  Primary_Transport               100000 non-null  str
 14  Public_Transport_Usage_Minutes  100000 non-null  int64
 15  Electricity_Consumption_kWh     100000 non-null  float64
 16  Water_Consumption_Liters        100000 non-null  int64
 17  Internet_Usage_GB               100000 non-null  float64
 18  Online_Food_Orders              100000 non-null  int64
 19  Daily_Spending_INR              100000 non-null  float64
 20  Hospital_Visits                 100000 non-null  int64
 21  Emergency_Complaints            100000 non-null  int64
 22  Work_Hours                      100000 non-null  float64
 23  Outdoor_Activity_Hours          100000 non-null  float64
 24  Happiness_Score                 100000 non-null  float64
 25  Service_Satisfaction            100000 non-null  float64
 26  Weekend                         100000 non-null  str
 27  Month                           100000 non-null  int64
 28  Year                            100000 non-null  int64
 29  Day                             100000 non-null  int64
 30  Month_Name                      100000 non-null  str
 31  Quarter                         100000 non-null  int64
dtypes: float64(11), int64(9), str(12)
memory usage: 24.4 MB

In [6]:
dc.describe()

,Temperature_C,Rainfall_mm,AQI,Average_Traffic_Speed_kmh,Public_Transport_Usage_Minutes,Electricity_Consumption_kWh,Water_Consumption_Liters,Internet_Usage_GB,Online_Food_Orders,Daily_Spending_INR,Hospital_Visits,Emergency_Complaints,Work_Hours,Outdoor_Activity_Hours,Happiness_Score,Service_Satisfaction,Month,Year,Day,Quarter
count,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000
mean,27.122641,3.664261,115.652720,27.924011,30.764970,9.884848,144.450540,3.836436,0.630160,1016.597123,0.001480,0.034740,6.601462,2.077842,7.700595,7.663431,6.536080,2023.998890,15.729420,2.513120
std,5.535933,5.653815,47.424984,13.508682,39.548256,3.077680,44.872812,2.030874,0.756944,533.387149,0.038442,0.207542,2.364405,1.087854,1.062520,1.394511,3.454817,0.816441,8.803161,1.117846
min,6.800000,0.000000,20.000000,4.000000,0.000000,1.000000,20.000000,0.100000,0.000000,50.000000,0.000000,0.000000,0.000000,0.000000,3.000000,1.600000,1.000000,2023.000000,1.000000,1.000000
25%,23.000000,0.600000,82.000000,16.200000,0.000000,7.790000,114.000000,2.390000,0.000000,635.420000,0.000000,0.000000,5.200000,1.300000,7.000000,6.700000,4.000000,2023.000000,8.000000,2.000000
50%,27.100000,1.600000,114.000000,27.400000,0.000000,9.860000,145.000000,3.800000,0.000000,1005.105000,0.000000,0.000000,6.900000,2.100000,7.700000,7.700000,7.000000,2024.000000,16.000000,3.000000
75%,31.300000,4.000000,147.000000,37.400000,63.000000,11.950000,175.000000,5.220000,1.000000,1376.330000,0.000000,0.000000,8.300000,2.800000,8.400000,8.700000,10.000000,2025.000000,23.000000,4.000000
max,46.700000,92.400000,323.000000,55.000000,119.000000,22.820000,329.000000,14.150000,3.000000,3653.130000,1.000000,2.000000,11.000000,7.000000,10.000000,10.000000,12.000000,2025.000000,31.000000,4.000000

In [9]:
dc.dtypes

Record_ID                                    str
Date                              datetime64[us]
Day_Name                                     str
City                                         str
Area_Type                                    str
Citizen_ID                                   str
Age_Group                                    str
Work_Mode                                    str
Temperature_C                            float64
Rainfall_mm                              float64
AQI                                      float64
Traffic_Level                                str
Average_Traffic_Speed_kmh                float64
Primary_Transport                            str
Public_Transport_Usage_Minutes             int64
Electricity_Consumption_kWh              float64
Water_Consumption_Liters                   int64
Internet_Usage_GB                        float64
Online_Food_Orders                         int64
Daily_Spending_INR                       float64
Hospital_Visits                            int64
Emergency_Complaints                       int64
Work_Hours                               float64
Outdoor_Activity_Hours                   float64
Happiness_Score                          float64
Service_Satisfaction                     float64
Weekend                                      str
Month                                      int64
Year                                       int64
Day                                        int64
Month_Name                                   str
Quarter                                    int64
dtype: object

In [7]:
dc.isnull().sum()

Record_ID                         0
Date                              0
Day_Name                          0
City                              0
Area_Type                         0
Citizen_ID                        0
Age_Group                         0
Work_Mode                         0
Temperature_C                     0
Rainfall_mm                       0
AQI                               0
Traffic_Level                     0
Average_Traffic_Speed_kmh         0
Primary_Transport                 0
Public_Transport_Usage_Minutes    0
Electricity_Consumption_kWh       0
Water_Consumption_Liters          0
Internet_Usage_GB                 0
Online_Food_Orders                0
Daily_Spending_INR                0
Hospital_Visits                   0
Emergency_Complaints              0
Work_Hours                        0
Outdoor_Activity_Hours            0
Happiness_Score                   0
Service_Satisfaction              0
Weekend                           0
Month                             0
Year                              0
Day                               0
Month_Name                        0
Quarter                           0
dtype: int64

In [8]:
dc["Date"] = pd.to_datetime(dc["Date"])